# Generated by Django 4.0.5 on 2022-07-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
